import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import 'bootstrap/dist/css/bootstrap.min.css'; // Import bootstrap CSS
import '../public/css/responsive.css';
import '../public/css/style.css';
import '../public/css/swiper-bundle.min.css';
import '../public/css/bootstrap.min.css';

import '../public/css/owl.carousel.min.css';
import '../public/css/owl.theme.default.min.css';

import './globals.css';

import Head from 'next/head';
import Script from 'next/script';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        {/* <script
          src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
          integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
          crossOrigin="anonymous"
        ></script> */}
        <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
        <Script
          src={`/js/swiper-bundle.min.js`}
          // strategy="lazyOnload"
        />
        <Script
          src={`/js/jquery-3.3.1.min.js`}
          strategy="beforeInteractive"
        />

        <Script
          src={`/js/owl.carousel.js`}
          strategy="beforeInteractive"
        />
      </body>
    </html>
  );
}
